import type { Route } from "./+types/tos";
import { Navbar } from "~/components/layout/navbar";
import { Footer } from "~/components/layout/footer";

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Terms of Service — Donkey SEO" },
    {
      name: "description",
      content:
        "Terms of Service for Donkey SEO — AI-powered SEO content pipeline.",
    },
  ];
}

export default function TermsOfService() {
  return (
    <>
      <Navbar />
      <main className="section-container py-20">
        <article className="prose prose-neutral dark:prose-invert mx-auto max-w-3xl">
          <h1 className="font-display">Terms of Service</h1>
          <p className="text-muted-foreground text-sm">
            Last updated: 25 February 2026
          </p>

          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using Donkey SEO ("the Service"), you agree to be
            bound by these Terms of Service. If you do not agree to these terms,
            please do not use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            Donkey SEO provides an AI-powered SEO content pipeline that enables
            website owners to automate their SEO strategy — from keyword research
            and content discovery to article generation and CMS delivery. The
            Service includes the dashboard, content pipeline, integrations, and
            related tools.
          </p>

          <h2>3. Account Registration</h2>
          <p>
            To use certain features of the Service, you must register for an
            account. You agree to provide accurate, current, and complete
            information and to keep this information up to date. You are
            responsible for maintaining the confidentiality of your account
            credentials.
          </p>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to use the Service to:</p>
          <ul>
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe on the rights of others</li>
            <li>Generate spam, misleading, or harmful content</li>
            <li>Distribute malware or harmful code</li>
            <li>
              Attempt to gain unauthorised access to the Service or related
              systems
            </li>
            <li>Interfere with the proper functioning of the Service</li>
            <li>
              Use generated content in a way that violates third-party
              intellectual property rights
            </li>
          </ul>

          <h2>5. Generated Content and Intellectual Property</h2>
          <p>
            The Service and its original features and functionality are owned by
            Donkey SEO and are protected by international copyright, trademark,
            and other intellectual property laws. Content generated by the
            Service on your behalf is yours to use. However, you are responsible
            for reviewing and ensuring the accuracy and appropriateness of all
            generated content before publication.
          </p>

          <h2>6. Payment and Subscriptions</h2>
          <p>
            Some features of the Service require a paid subscription. Payments
            are processed securely, and by subscribing you agree to pay the
            applicable fees. Subscriptions renew automatically unless cancelled
            before the renewal date. Refunds are handled in accordance with
            applicable consumer protection laws.
          </p>

          <h2>7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable law, Donkey SEO shall
            not be liable for any indirect, incidental, special, consequential,
            or punitive damages, or any loss of profits or revenues, whether
            incurred directly or indirectly, or any loss of data, use, goodwill,
            or other intangible losses resulting from your use of the Service.
            Donkey SEO is not responsible for the performance of content
            generated by the Service in search engine rankings or any other
            third-party platform.
          </p>

          <h2>8. Disclaimer of Warranties</h2>
          <p>
            The Service is provided "as is" and "as available" without warranties
            of any kind, either express or implied, including but not limited to
            implied warranties of merchantability, fitness for a particular
            purpose, and non-infringement. We do not guarantee specific SEO
            results, search engine rankings, or traffic outcomes.
          </p>

          <h2>9. Termination</h2>
          <p>
            We may terminate or suspend your account and access to the Service
            immediately, without prior notice, for conduct that we believe
            violates these Terms or is harmful to other users, us, or third
            parties, or for any other reason at our sole discretion.
          </p>

          <h2>10. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will
            notify users of any material changes by posting the new Terms on
            this page and updating the "Last updated" date. Your continued use of
            the Service after any changes constitutes acceptance of the new
            Terms.
          </p>

          <h2>11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the
            laws of the European Union and applicable member state laws, without
            regard to conflict of law provisions. For consumers within the EU,
            mandatory consumer protection laws of your country of residence shall
            apply.
          </p>

          <h2>12. Contact</h2>
          <p>
            If you have any questions about these Terms, please contact us at{" "}
            <a href="mailto:support@donkeyseo.com">support@donkeyseo.com</a>.
          </p>
        </article>
      </main>
      <Footer />
    </>
  );
}
